# Generated by Django 5.0 on 2025-06-07 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IndexPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('privacy_link', models.CharField(max_length=100)),
                ('window_w', models.CharField(max_length=100)),
                ('running_line', models.CharField(max_length=200)),
                ('enable_running_line', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Настройки главной страницы',
            },
        ),
    ]
