# Generated by Django 5.0 on 2025-06-07 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indexpage',
            name='enable_running_line',
            field=models.BooleanField(default=True, verbose_name='Включить бегущую строку'),
        ),
        migrations.AlterField(
            model_name='indexpage',
            name='privacy_link',
            field=models.CharField(max_length=100, verbose_name='Политика конфиденциальности'),
        ),
        migrations.AlterField(
            model_name='indexpage',
            name='running_line',
            field=models.CharField(max_length=200, verbose_name='Бегущая строка'),
        ),
        migrations.AlterField(
            model_name='indexpage',
            name='title',
            field=models.CharField(max_length=50, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='indexpage',
            name='window_w',
            field=models.CharField(max_length=100, verbose_name='Окно W'),
        ),
    ]
