# Generated by Django 5.0 on 2025-06-07 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kviz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.SmallIntegerField(default=1)),
                ('communication_methods', models.CharField(max_length=10, null=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='client',
            options={'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.RemoveField(
            model_name='client',
            name='communication_methods',
        ),
        migrations.RemoveField(
            model_name='client',
            name='unique_key',
        ),
        migrations.AlterField(
            model_name='client',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='username',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.DeleteModel(
            name='Answer',
        ),
    ]
