# Generated by Django 5.0 on 2025-06-07 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_kviz_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='nickname',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
