# Generated by Django 5.0 on 2025-06-07 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_client_nickname'),
    ]

    operations = [
        migrations.AddField(
            model_name='kviz',
            name='phone',
            field=models.CharField(max_length=50, null=True, verbose_name='Телефон'),
        ),
    ]
