# Generated by Django 5.0 on 2025-06-07 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_kviz_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='kviz',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
