# Generated by Django 5.0 on 2025-06-08 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_kviz_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='kviz',
            name='interes',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
