# Generated by Django 5.0 on 2025-06-08 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_kviz_interes'),
    ]

    operations = [
        migrations.AddField(
            model_name='kviz',
            name='profession',
            field=models.CharField(max_length=50, null=True, verbose_name='Профессия'),
        ),
        migrations.AlterField(
            model_name='kviz',
            name='interes',
            field=models.CharField(max_length=50, null=True, verbose_name='Что интересует'),
        ),
    ]
