# Generated by Django 5.0 on 2025-06-08 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_kviz_profession_alter_kviz_interes'),
    ]

    operations = [
        migrations.AddField(
            model_name='kviz',
            name='work_experience',
            field=models.CharField(max_length=50, null=True, verbose_name='Опыт работы'),
        ),
    ]
