# Generated by Django 5.0 on 2025-06-08 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_kviz_work_experience'),
    ]

    operations = [
        migrations.AddField(
            model_name='kviz',
            name='birth_year',
            field=models.CharField(max_length=50, null=True, verbose_name='Год рождения'),
        ),
    ]
