# Generated by Django 5.0 on 2025-06-08 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_kviz_citizenship_kviz_min_zp_kviz_residence_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kviz',
            name='responsible',
            field=models.BooleanField(null=True, verbose_name='Ответственный'),
        ),
    ]
