# Generated by Django 5.0 on 2025-06-08 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_kviz_responsible'),
    ]

    operations = [
        migrations.AddField(
            model_name='kviz',
            name='brigada',
            field=models.BooleanField(null=True, verbose_name='Бригада'),
        ),
        migrations.AddField(
            model_name='kviz',
            name='car',
            field=models.BooleanField(null=True, verbose_name='Авто'),
        ),
        migrations.AddField(
            model_name='kviz',
            name='have_ip',
            field=models.BooleanField(null=True, verbose_name='СЗ/ИП'),
        ),
        migrations.AddField(
            model_name='kviz',
            name='instrument',
            field=models.BooleanField(null=True, verbose_name='Инструмент'),
        ),
        migrations.AddField(
            model_name='kviz',
            name='partner',
            field=models.BooleanField(null=True, verbose_name='Есть напарник'),
        ),
        migrations.AddField(
            model_name='kviz',
            name='rate_work',
            field=models.BooleanField(null=True, verbose_name='Оценка объекта'),
        ),
    ]
