# Generated by Django 5.0 on 2025-06-08 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_kviz_brigada_kviz_car_kviz_have_ip_kviz_instrument_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kviz',
            name='any_job',
            field=models.BooleanField(null=True, verbose_name='Интересует любая работа'),
        ),
        migrations.AddField(
            model_name='kviz',
            name='dayly_pay',
            field=models.BooleanField(null=True, verbose_name='Интересует ежедневная оплата'),
        ),
        migrations.AddField(
            model_name='kviz',
            name='job_without_registration',
            field=models.BooleanField(null=True, verbose_name='Интересует работа без оформления'),
        ),
        migrations.AddField(
            model_name='kviz',
            name='permanent_job',
            field=models.BooleanField(null=True, verbose_name='Интересует постоянная работа'),
        ),
        migrations.AddField(
            model_name='kviz',
            name='piecework_payment',
            field=models.BooleanField(null=True, verbose_name='Интересует сдельная оплата'),
        ),
        migrations.AddField(
            model_name='kviz',
            name='schedulefivetwo',
            field=models.BooleanField(null=True, verbose_name='Интересует график 5/2'),
        ),
        migrations.AddField(
            model_name='kviz',
            name='shift_schedule',
            field=models.BooleanField(null=True, verbose_name='Интересует сменный график'),
        ),
        migrations.AddField(
            model_name='kviz',
            name='temporary_job',
            field=models.BooleanField(null=True, verbose_name='Интересует временная работа'),
        ),
    ]
