# Generated by Django 5.0 on 2025-06-09 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_kviz_any_job_kviz_dayly_pay_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kviz',
            options={'verbose_name': 'Опрос', 'verbose_name_plural': 'Опросы'},
        ),
        migrations.AddField(
            model_name='kviz',
            name='another_skills',
            field=models.BooleanField(null=True, verbose_name='Другие преимущества'),
        ),
    ]
