# Generated by Django 5.0 on 2025-06-09 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_alter_kviz_options_kviz_another_skills'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kviz',
            name='another_skills',
            field=models.CharField(max_length=200, null=True, verbose_name='Другие преимущества'),
        ),
    ]
