# Generated by Django 5.0 on 2025-06-09 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_alter_kviz_another_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='kviz',
            name='NAKCT',
            field=models.BooleanField(null=True, verbose_name='НАКСТ'),
        ),
    ]
