# Generated by Django 5.0 on 2025-06-09 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_kviz_nakct'),
    ]

    operations = [
        migrations.AddField(
            model_name='kviz',
            name='foam_glass_installation',
            field=models.BooleanField(null=True, verbose_name='Монтаж пеностекла'),
        ),
        migrations.AddField(
            model_name='kviz',
            name='installation_PPU_shell',
            field=models.BooleanField(null=True, verbose_name='Монтаж ППУ скорлупы'),
        ),
        migrations.AddField(
            model_name='kviz',
            name='installation_foil_cylinders',
            field=models.BooleanField(null=True, verbose_name='Монтаж фольг. цилиндров'),
        ),
        migrations.AddField(
            model_name='kviz',
            name='installation_kflex',
            field=models.BooleanField(null=True, verbose_name='Монтаж K-Flex'),
        ),
        migrations.AddField(
            model_name='kviz',
            name='installation_window_frame',
            field=models.BooleanField(null=True, verbose_name='Монтаж окожушки'),
        ),
        migrations.AddField(
            model_name='kviz',
            name='manufacture_shell',
            field=models.BooleanField(null=True, verbose_name='Изготовление окожушки'),
        ),
        migrations.AddField(
            model_name='kviz',
            name='spraying_PPU',
            field=models.BooleanField(null=True, verbose_name='Напыление ППУ'),
        ),
    ]
