# Generated by Django 5.0 on 2025-06-09 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_kviz_foam_glass_installation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kviz',
            name='another_installer_skills',
            field=models.CharField(max_length=200, null=True, verbose_name='Другие навыки'),
        ),
    ]
