# Generated by Django 5.0 on 2025-06-09 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_kviz_another_installer_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='kviz',
            name='airducts',
            field=models.BooleanField(null=True, verbose_name='Воздуховоды'),
        ),
        migrations.AddField(
            model_name='kviz',
            name='another_can_installer_skills',
            field=models.CharField(max_length=200, null=True, verbose_name='Что другое умеет изолировать'),
        ),
        migrations.AddField(
            model_name='kviz',
            name='equipment',
            field=models.BooleanField(null=True, verbose_name='Оборудование'),
        ),
        migrations.AddField(
            model_name='kviz',
            name='pipelines',
            field=models.BooleanField(null=True, verbose_name='Трубопроводы'),
        ),
        migrations.AddField(
            model_name='kviz',
            name='reservoirs',
            field=models.BooleanField(null=True, verbose_name='Резервуары'),
        ),
    ]
