# Generated by Django 5.0 on 2025-06-09 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_kviz_airducts_kviz_another_can_installer_skills_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kviz',
            name='another_welding',
            field=models.CharField(max_length=200, null=True, verbose_name='Другие виды сварки'),
        ),
        migrations.AddField(
            model_name='kviz',
            name='argon',
            field=models.BooleanField(null=True, verbose_name='Аргоновая'),
        ),
        migrations.AddField(
            model_name='kviz',
            name='gasfired',
            field=models.BooleanField(null=True, verbose_name='Газовая'),
        ),
        migrations.AddField(
            model_name='kviz',
            name='manual_electric_arc',
            field=models.BooleanField(null=True, verbose_name='Ручная электродуговая'),
        ),
        migrations.AddField(
            model_name='kviz',
            name='plasma',
            field=models.BooleanField(null=True, verbose_name='Плазменная'),
        ),
        migrations.AddField(
            model_name='kviz',
            name='semiautomatic',
            field=models.BooleanField(null=True, verbose_name='Полуавтоматическая'),
        ),
        migrations.AddField(
            model_name='kviz',
            name='welding_gas_environment',
            field=models.BooleanField(null=True, verbose_name='Сварка в среде газа'),
        ),
    ]
