# Generated by Django 5.0 on 2025-06-09 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_kviz_another_welding_kviz_argon_kviz_gasfired_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kviz',
            name='can_weld_another',
            field=models.CharField(max_length=200, null=True, verbose_name='Другие конструкции'),
        ),
        migrations.AddField(
            model_name='kviz',
            name='can_weld_building_frames',
            field=models.BooleanField(null=True, verbose_name='Каркасы зданий'),
        ),
        migrations.AddField(
            model_name='kviz',
            name='can_weld_columns',
            field=models.BooleanField(null=True, verbose_name='Балки, колонны'),
        ),
        migrations.AddField(
            model_name='kviz',
            name='can_weld_energy_boilers',
            field=models.BooleanField(null=True, verbose_name='Энергетические котлы'),
        ),
        migrations.AddField(
            model_name='kviz',
            name='can_weld_equipment',
            field=models.BooleanField(null=True, verbose_name='Оборудование'),
        ),
        migrations.AddField(
            model_name='kviz',
            name='can_weld_pipelines',
            field=models.BooleanField(null=True, verbose_name='Трубопроводы'),
        ),
        migrations.AddField(
            model_name='kviz',
            name='can_weld_simple_constructions',
            field=models.BooleanField(null=True, verbose_name='Простые конструкции'),
        ),
    ]
