# Generated by Django 5.0 on 2025-06-09 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_kviz_can_weld_another_kviz_can_weld_building_frames_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kviz',
            name='conducting_hydrotests',
            field=models.BooleanField(null=True, verbose_name='Провожу гидроиспытания'),
        ),
        migrations.AddField(
            model_name='kviz',
            name='know_norms_standards',
            field=models.BooleanField(null=True, verbose_name='Знаю нормы и стандарты'),
        ),
        migrations.AddField(
            model_name='kviz',
            name='organizational_skills',
            field=models.BooleanField(null=True, verbose_name='Организаторские навыки'),
        ),
        migrations.AddField(
            model_name='kviz',
            name='read_drawings_diagrams',
            field=models.BooleanField(null=True, verbose_name='Читаю чертежи и схемы'),
        ),
        migrations.AddField(
            model_name='kviz',
            name='working_with_tools',
            field=models.BooleanField(null=True, verbose_name='Работа с инструментами'),
        ),
    ]
