# Generated by Django 5.0 on 2025-06-09 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_kviz_conducting_hydrotests_kviz_know_norms_standards_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kviz',
            name='another_insulator_skills',
            field=models.CharField(max_length=200, null=True, verbose_name='Другие навыки'),
        ),
    ]
