# Generated by Django 5.0 on 2025-06-09 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_kviz_another_insulator_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='kviz',
            name='IP',
            field=models.BooleanField(null=True, verbose_name='ИП'),
        ),
        migrations.AddField(
            model_name='kviz',
            name='OOO',
            field=models.BooleanField(null=True, verbose_name='ООО'),
        ),
    ]
