# Generated by Django 5.0 on 2025-06-09 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_kviz_ip_kviz_ooo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kviz',
            name='IP',
        ),
        migrations.RemoveField(
            model_name='kviz',
            name='OOO',
        ),
        migrations.AddField(
            model_name='kviz',
            name='OPF',
            field=models.CharField(max_length=3, null=True, verbose_name='ОПФ'),
        ),
    ]
