# Generated by Django 5.0 on 2025-06-09 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_remove_kviz_ip_remove_kviz_ooo_kviz_opf'),
    ]

    operations = [
        migrations.AddField(
            model_name='kviz',
            name='activity_direction',
            field=models.CharField(max_length=200, null=True, verbose_name='Направление деятельности'),
        ),
        migrations.AddField(
            model_name='kviz',
            name='activity_region',
            field=models.CharField(max_length=200, null=True, verbose_name='Регион/Город'),
        ),
    ]
