# Generated by Django 5.0 on 2025-06-09 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_kviz_activity_direction_kviz_activity_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='kviz',
            name='ceh_count',
            field=models.CharField(max_length=200, null=True, verbose_name='Численность персонала'),
        ),
        migrations.AddField(
            model_name='kviz',
            name='contract_price',
            field=models.CharField(max_length=200, null=True, verbose_name='Цена контрактов'),
        ),
    ]
