# Generated by Django 5.0 on 2025-06-09 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_kviz_interest_professions_kviz_region_professions'),
    ]

    operations = [
        migrations.AddField(
            model_name='kviz',
            name='email_form2',
            field=models.CharField(max_length=200, null=True, verbose_name='e-mai Форма 2'),
        ),
        migrations.AddField(
            model_name='kviz',
            name='message_form2',
            field=models.CharField(max_length=200, null=True, verbose_name='Сообщение Форма 2'),
        ),
        migrations.AddField(
            model_name='kviz',
            name='organization_form2',
            field=models.CharField(max_length=200, null=True, verbose_name='Организация Форма 2'),
        ),
    ]
