# Generated by Django 5.0 on 2025-06-09 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_kviz_email_form2_kviz_message_form2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kviz',
            name='has_work',
            field=models.CharField(max_length=200, null=True, verbose_name='Есть основная работа'),
        ),
        migrations.AddField(
            model_name='kviz',
            name='has_work_another',
            field=models.CharField(max_length=200, null=True, verbose_name='Есть основная работа (Другое)'),
        ),
    ]
