# Generated by Django 5.0 on 2025-06-09 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_kviz_has_work_kviz_has_work_another'),
    ]

    operations = [
        migrations.AddField(
            model_name='kviz',
            name='work_another',
            field=models.CharField(max_length=200, null=True, verbose_name='Какая работа Вас интересует? (Другое)'),
        ),
    ]
