# Generated by Django 5.0 on 2025-06-10 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0033_kviz_call_kviz_tg_kviz_vk_kviz_whatsapp'),
    ]

    operations = [
        migrations.AddField(
            model_name='kviz',
            name='another_object_region',
            field=models.CharField(max_length=200, null=True, verbose_name='регион объекта (Другое)'),
        ),
        migrations.AddField(
            model_name='kviz',
            name='object_region',
            field=models.CharField(max_length=200, null=True, verbose_name='регион объекта'),
        ),
    ]
