# Generated by Django 5.1.6 on 2025-06-12 06:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0034_kviz_another_object_region_kviz_object_region'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kviz',
            name='communication_methods',
        ),
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='имя')),
                ('title', models.CharField(max_length=150, verbose_name='заголовок')),
                ('type', models.CharField(choices=[('radio', 'radio'), ('checkbox', 'checkbox'), ('text', 'text')], max_length=10)),
                ('another_field', models.CharField(blank=True, max_length=50, null=True)),
                ('next', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.form')),
            ],
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=50, verbose_name='текст')),
                ('field', models.CharField(max_length=50, verbose_name='поле')),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='main.form')),
                ('next', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.form')),
            ],
        ),
    ]
