# Generated by Django 5.1.6 on 2025-06-12 06:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0035_remove_kviz_communication_methods_form_option'),
    ]

    operations = [
        migrations.AlterField(
            model_name='option',
            name='field',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='поле'),
        ),
        migrations.AlterField(
            model_name='option',
            name='next',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.form'),
        ),
    ]
