# Generated by Django 5.1.6 on 2025-06-12 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0036_alter_option_field_alter_option_next'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='form',
            options={'ordering': ['title'], 'verbose_name': 'Форма', 'verbose_name_plural': 'Формы'},
        ),
        migrations.RemoveField(
            model_name='client',
            name='name',
        ),
    ]
