# Generated by Django 5.1.6 on 2025-06-12 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0037_alter_form_options_remove_client_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='kviz',
            name='name',
            field=models.CharField(max_length=50, null=True, verbose_name='Имя, которое указал пользователь'),
        ),
    ]
