# Generated by Django 5.1.6 on 2025-06-12 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0038_kviz_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='kviz',
            name='ceiling_installation',
            field=models.BooleanField(null=True, verbose_name='Монтаж потолков'),
        ),
        migrations.AddField(
            model_name='kviz',
            name='comprehensive_finishing',
            field=models.BooleanField(null=True, verbose_name='Комплексная отделка'),
        ),
        migrations.AddField(
            model_name='kviz',
            name='installation_doors_and_windows',
            field=models.BooleanField(null=True, verbose_name='Установка дверей и окон'),
        ),
        migrations.AddField(
            model_name='kviz',
            name='installation_drywall',
            field=models.BooleanField(null=True, verbose_name='Монтаж гипсокартона'),
        ),
        migrations.AddField(
            model_name='kviz',
            name='laying_tiles',
            field=models.BooleanField(null=True, verbose_name='Укладка плитки'),
        ),
        migrations.AddField(
            model_name='kviz',
            name='painting_work',
            field=models.BooleanField(null=True, verbose_name='Малярные работы'),
        ),
        migrations.AddField(
            model_name='kviz',
            name='plastering_works',
            field=models.BooleanField(null=True, verbose_name='Штукатурные работы'),
        ),
        migrations.AddField(
            model_name='kviz',
            name='wallpapering',
            field=models.BooleanField(null=True, verbose_name='Оклейка обоями'),
        ),
    ]
