# Generated by Django 5.1.6 on 2025-06-12 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0039_kviz_ceiling_installation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='show_next',
            field=models.BooleanField(default=False, verbose_name='Показывать следующее'),
        ),
        migrations.AddField(
            model_name='kviz',
            name='metro',
            field=models.CharField(max_length=200, null=True, verbose_name='Метро'),
        ),
    ]
