# Generated by Django 5.1.6 on 2025-06-13 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0040_form_show_next_kviz_metro'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='user_id',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
