# Generated by Django 5.1.6 on 2025-06-13 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0041_client_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='kviz',
            name='another_finisher',
            field=models.CharField(max_length=200, null=True, verbose_name='Отделочник (другое)'),
        ),
    ]
